### ISSUE TITLE
Arrow keys

### ISSUE THREAD

**Issue by vladdoster** [hericlesme/i-just-want-to-play-tetris#1]
When I try to use the arrow keys to control movement it scrolls up and down the page which makes me lost sight of the tetris board. How do you get around the issue?

**Comment by hericlesme** [comment]
The screen shouldn't scroll. Could you give me a print or more details? :thinking:

**Comment by vladdoster** [comment]
Yes, about to get into a flight so a bit later in the day. I saw on the version you have running on your domain that it doesn't scroll.

**Comment by hericlesme** [comment]
What is the resolution of your screen?

**Comment by vladdoster** [comment]
1080p

**Comment by vladdoster** [comment]
Huh, so I figured out the issue somewhat. Since I run a tiling window manager I think it is getting the viewport messed up. When I move it to a different workspace and it has the whole screen to stretch out into it works no problems. 

![pic-full-200315-1159-42](https://user-images.githubusercontent.com/10052309/76705193-8df4d280-66b4-11ea-82c9-4c204f6df6cc.png)

**Comment by vladdoster** [comment]
Just thought I'd bring it up. Closing this issue.
